apiVersion: v1
kind: Service
metadata:
  name: devops-sample-app
  namespace: devops-lab-gitops-dev
  labels:
    app: devops-sample-app
    environment: dev
    managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: devops-sample-app
    environment: dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080