aws_region           = "ca-central-1"
project_name         = "Devops-lab"
environment          = "prod"
vpc_cidr             = "10.30.0.0/16"
availability_zones   = ["ca-central-1a", "ca-central-1b"]
public_subnet_cidrs  = ["10.30.1.0/24", "10.30.2.0/24"]
private_subnet_cidrs = ["10.30.3.0/24", "10.30.4.0/24"]
enable_nat_gateway   = true
allowed_ssh_cidr     = "10.30.0.0/16"
common_tags = {
  owner           = "Ronak"
  Environment     = "prod"
  Project         = "Devops-production-lab"
  costCenter      = "DevOps-Lab"
  ManagedBy       = "Terraform"
  criticality     = "high"
  dataclass       = "Internal"
  backupRequired  = "true"
  ComplianceScope = "Production-Simulation"
}