apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-sample-app-config
  namespace: devops-lab
  labels:
    app: devops-sample-app
    environment: dev
data:
  APP_ENV: "kubernetes-dev"
  APP_NAME: "devops-production-lab"
  APP_VERSION: "1.0.0"
  Log_Level: "INFO"