apiVersion: v1
kind: Service
metadata:
  name: devops-sample-app-service
  namespace: devops-lab
  labels:
    app: devops-sample-app
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: devops-sample-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080