apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample-app
  namespace: devops-lab
  labels:
    app: devops-sample-app
    environment: dev
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: devops-sample-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: devops-sample-app
        environment: dev
    spec:
      containers:
        - name: devops-sample-app
          image: devops-sample-app:prod
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo Simulating crash && exit 1"]
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: devops-sample-app-config
            - secretRef:
                name: devops-sample-app-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3